<?php

namespace Container4BtxzdC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OVKq5doService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OVKq5do' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OVKq5do'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', '.errored.ZNrbsUy', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::delete()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UserRepository".'],
        ], [
            'passwordHasher' => '?',
            'userRepository' => '?',
        ]);
    }
}
