<?php

namespace Container4BtxzdC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCroquetteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CroquetteController' shared autowired service.
     *
     * @return \App\Controller\CroquetteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CroquetteController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Helpers/CheckHelper.php';

        $container->services['App\\Controller\\CroquetteController'] = $instance = new \App\Controller\CroquetteController(($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->services['doctrine'] ?? $container->load('getDoctrineService')), ($container->privates['App\\Controller\\Helpers\\CheckHelper'] ??= new \App\Controller\Helpers\CheckHelper()), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\CroquetteController', $container));

        return $instance;
    }
}
