<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKz8IBYf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKz8IBYf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKz8IBYf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKz8IBYf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKz8IBYf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kz8IBYf',
    'container.build_id' => 'ce665400',
    'container.build_time' => 1682070142,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKz8IBYf');
