<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArWkBto\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArWkBto/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerArWkBto.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerArWkBto\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerArWkBto\App_KernelDevDebugContainer([
    'container.build_hash' => 'ArWkBto',
    'container.build_id' => '9915e5ad',
    'container.build_time' => 1682342895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArWkBto');
