<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'croquette_analyse' => [[], ['_controller' => 'App\\Controller\\AnalyseController::analyseAll'], [], [['text', '/api/v1/analyse']], [], [], []],
    'croquette_analyseOne' => [['id'], ['_controller' => 'App\\Controller\\AnalyseController::analyseOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/analyse']], [], [], []],
    'marque_list' => [[], ['_controller' => 'App\\Controller\\BrandController::index'], [], [['text', '/api/v1/brand']], [], [], []],
    'croquette_list' => [[], ['_controller' => 'App\\Controller\\CroquetteController::list'], [], [['text', '/api/v1/croquette']], [], [], []],
    'croquette_show' => [['id'], ['_controller' => 'App\\Controller\\CroquetteController::showOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/croquette']], [], [], []],
    'marque_show' => [['brand'], ['_controller' => 'App\\Controller\\CroquetteController::showByBrand'], [], [['variable', '/', '[^/]++', 'brand', true], ['text', '/api/v1/croquette_by_brand']], [], [], []],
    'security_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/v1/register']], [], [], []],
    'security_reset' => [[], ['_controller' => 'App\\Controller\\SecurityController::reset'], [], [['text', '/api/v1/reset']], [], [], []],
    'security_delete' => [[], ['_controller' => 'App\\Controller\\SecurityController::delete'], [], [['text', '/api/v1/delete']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/v1/login_check']], [], [], []],
];
